apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fh-swf-ingress
spec:
  rules:
  - host: mcp.fh-swf.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fh-swf-mcp-service-prod
            port:
              number: 8000
