apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-fh-swf-prod

bases:
  - ../../base

nameSuffix: -prod

replicas:
  - name: fh-swf-mcp-deployment
    count: 2
  - name: neo4j
    count: 1

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: fh-swf-mcp
    newName: ghcr.io/fhswf/mcp_fh-swf
    newTag: "${RELEASE_VERSION}"  # wird durch CI/CD automatisch gesetzt

commonLabels:
  environment: prod
  branch: prod
