apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  labels:
    io.kubernetes.part-of: mcp_fh_swf
    app: fh-swf-mcp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-filesystem